### ISSUE TITLE
HTML contents overflow the output area

### ISSUE THREAD

**Issue by munierujp** [munierujp/text2html#3]
## Example
<img width="1072" alt="2018-05-09 23 32 52" src="https://user-images.githubusercontent.com/20086673/39820684-59f0dd86-53e1-11e8-8fe7-fa25d9e510ed.png">

## FYI
```css
#main {
  display: flex;
  overflow-wrap: break-word;
}

#output {
  flex: 1;
  overflow-y: scroll;
  min-width: 0;
}
```
